language: node_js
node_js: 
  - "8.11"
install:
  - npm install
script:
 - npm test
 addons:
   chrone: stable
before_install:
  -google-chrome-stable  --headless --disable-gpu --remote-debugging-port=922 http://localhost &
beforescript:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo cmd 4755 /opt/google/chrome/chrome-sandbox"